// Cloudflare Worker entry: the OpenNext app, plus a cron trigger for the daily reminder emails.
// The schedule is in wrangler.json ("triggers"); the job itself is app/api/cron/reminders.
// .open-next/worker.js is generated by `opennextjs-cloudflare build`, so this file is left out of tsc/eslint.

import { default as handler } from './.open-next/worker.js';

interface Env {
  CRON_SECRET?: string;
  [key: string]: unknown;
}
interface Ctx {
  waitUntil(promise: Promise<unknown>): void;
}

export default {
  fetch: handler.fetch,

  async scheduled(_event: unknown, env: Env, ctx: Ctx) {
    const request = new Request('https://itsfootball.club/api/cron/reminders', {
      method: 'POST',
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ''}` },
    });
    ctx.waitUntil(
      handler.fetch(request, env, ctx).then(async (res: Response) => {
        console.log(`[cron] reminders ${res.status}: ${await res.text()}`);
      })
    );
  },
};

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';
