// Columns sent to Supabase for each synced table (generated from lib/supabase/types.ts).
// Client-only fields (e.g. member passwords / magic tokens) are intentionally NOT listed so they
// are never written to the database.
export const TABLE_COLUMNS: Record<string, string[]> = {
  clubs: ['id', 'owner_id', 'slug', 'name', 'short_name', 'motto', 'founded_year', 'logo_url', 'banner_url', 'slider_images', 'hero_pinned_items', 'primary_color', 'secondary_color', 'accent_color', 'stadium_name', 'stadium_address', 'stadium_lat', 'stadium_lng', 'stadium_capacity', 'stadium_pitch_type', 'stadium_parking_info', 'contact_email', 'contact_phone', 'custom_domain', 'previous_slugs', 'current_season_id', 'config', 'is_active', 'created_at', 'updated_at'],
  club_members: ['id', 'club_id', 'user_id', 'first_name', 'last_name', 'full_name', 'email', 'phone', 'role', 'roles', 'player_position', 'secondary_positions', 'jersey_number', 'photo_url', 'date_of_birth', 'nationality', 'preferred_foot', 'height_cm', 'weight_kg', 'status', 'membership_status', 'applied_at', 'reviewed_at', 'reviewed_by', 'rejection_reason', 'application_notes', 'emergency_contact', 'qr_code_token', 'membership_tier', 'membership_expires_at', 'is_executive', 'executive_title', 'executive_bio', 'executive_order', 'executive_season', 'created_at', 'updated_at'],
  player_stats: ['id', 'club_id', 'member_id', 'season', 'appearances', 'minutes_played', 'goals', 'assists', 'clean_sheets', 'yellow_cards', 'red_cards', 'motm_awards'],
  matches: ['id', 'club_id', 'title', 'match_type', 'competition', 'season', 'opponent_name', 'opponent_short_name', 'home_team_name', 'away_team_name', 'home_team_logo', 'away_team_logo', 'is_club_home', 'match_date', 'match_time', 'venue', 'match_flyer_url', 'description', 'status', 'featured_on_hero', 'door_qr_checkin_enabled', 'checkin_count', 'home_score', 'away_score', 'current_minute', 'is_paused', 'added_time', 'period', 'home_formation', 'away_formation', 'home_lineup_coords', 'away_lineup_coords', 'period_started_at', 'match_format', 'is_audited', 'audited_at', 'tournament_id', 'tournament_stage', 'tournament_group', 'tournament_round', 'tournament_match_number', 'home_team_source', 'away_team_source', 'home_penalty_score', 'away_penalty_score', 'winner_side', 'next_match_id', 'next_match_slot', 'created_at'],
  match_events: ['id', 'match_id', 'club_id', 'minute', 'added_minute', 'event_type', 'team_side', 'player_name', 'assist_player_name', 'detail_text', 'created_at'],
  events: ['id', 'club_id', 'title', 'description', 'category', 'season', 'start_time', 'end_time', 'location', 'max_capacity', 'rsvp_count', 'is_public', 'door_qr_checkin_enabled', 'created_at'],
  sponsors: ['id', 'club_id', 'event_id', 'name', 'logo_url', 'website_url', 'tier', 'size_scale', 'display_order', 'is_active', 'contact_name', 'contact_email', 'contact_phone', 'package_value', 'package_status', 'season'],
  news_articles: ['id', 'club_id', 'title', 'slug', 'summary', 'content', 'cover_image_url', 'video_embed_url', 'author_name', 'tags', 'is_featured', 'published_at'],
  media_gallery: ['id', 'club_id', 'title', 'media_type', 'media_url', 'thumbnail_url', 'album_name', 'created_at'],
  member_clubscore_profiles: ['id', 'club_id', 'member_id', 'season', 'total_points', 'weekly_points', 'monthly_points', 'current_streak', 'highest_streak', 'tier', 'badges', 'last_activity_date', 'streak_updated_at', 'created_at', 'updated_at'],
  gamification_activity_log: ['id', 'club_id', 'member_id', 'event_type', 'points_awarded', 'multiplier', 'final_points', 'description', 'reference_id', 'created_by', 'created_at'],
  clubscore_rules: ['id', 'club_id', 'points_training_checkin', 'points_social_checkin', 'points_match_appearance', 'points_goal_forward', 'points_goal_midfielder', 'points_goal_defender', 'points_assist', 'points_clean_sheet_gk_def', 'points_motm', 'points_yellow_card_penalty', 'points_red_card_penalty', 'streak_multiplier_3w', 'streak_multiplier_5w', 'streak_multiplier_10w', 'is_active'],
  player_availabilities: ['id', 'club_id', 'match_id', 'event_id', 'member_id', 'status', 'note', 'response_token', 'responded_at', 'created_at', 'updated_at'],
  draft_lineups: ['id', 'club_id', 'match_id', 'format', 'formation', 'lineup_coords', 'bench_member_ids', 'tactical_notes', 'is_published', 'published_at', 'created_at', 'updated_at'],
  club_seasons: ['id', 'club_id', 'name', 'start_date', 'end_date', 'is_current', 'status', 'notes', 'created_at', 'updated_at'],
  member_messages: ['id', 'club_id', 'member_id', 'sender_type', 'sender_name', 'sender_email', 'subject', 'category', 'content', 'is_read', 'created_at'],
  internal_teams: ['id', 'club_id', 'name', 'short_name', 'color', 'logo_url', 'cover_url', 'captain_id', 'coach_name', 'player_ids', 'created_at', 'updated_at'],
  tournaments: ['id', 'club_id', 'name', 'slug', 'season', 'format', 'status', 'points_win', 'points_draw', 'points_loss', 'group_count', 'teams_advancing_per_group', 'has_third_place_match', 'start_date', 'end_date', 'venue', 'description', 'banner_url', 'created_at', 'updated_at'],
  tournament_participants: ['id', 'tournament_id', 'team_type', 'internal_team_id', 'name', 'short_name', 'logo_url', 'color', 'seed', 'group'],
  gate_scans: ['id', 'club_id', 'scan_type', 'token', 'member_id', 'member_name', 'event_id', 'event_title', 'match_id', 'match_title', 'valid', 'scanned_at'],
  contact_inquiries: ['id', 'club_id', 'sender_name', 'sender_email', 'sender_phone', 'inquiry_type', 'message', 'status', 'created_at'],
};
